esphome:
  name: esp32-white-minimalist-module
  friendly_name: ESP32-white-minimalist-module

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s  # Avoids reboot if no client is connected

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "workroom"
    password: "robinho0d"

captive_portal:

web_server:
  port: 80  

# Define the LED GPIO pin
output:
  - platform: gpio
    pin: GPIO4  # Replace with the actual GPIO pin connected to your LED
    id: led_output

# Define the light component (Creates toggle button in Web UI)
light:
  - platform: binary
    output: led_output
    id: status_led
    name: "LED Toggle"

# Interval-based LED toggling (Every second)
interval:
  - interval: 1s
    then:
      - light.toggle: status_led