esphome:
  name: esp32-s3
  friendly_name: ESP32-S3
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG # sets the overall logging level, which if not specified defaults to DEBUG
  logs: 
    component: ERROR # sets the logging level for a specific item, in this case all components

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case WiFi connection fails
  ap:
    ssid: "workroom"
    password: "robinho0d"

captive_portal:

web_server:
  port: 80
  
sensor:
# Include all sensor devices in the single sensor: domain
# Display WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_signal_strength
    update_interval: 60s

# Output for the LED
output:
  - platform: gpio
    pin: GPIO14
    id: led_output

# Light component with Home Assistant integration
light:
  - platform: binary
    name: "Toggle LED"
    output: led_output
    id: led_light
    restore_mode: ALWAYS_OFF  # Defines LED state after power restore

# Binary sensor for the push button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Push Button"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: led_light

