# Read ADC voltage
sensor:
  - platform: adc
    pin: GPIO32  # Change this to your ADC pin
    name: "Measured Voltage"
    update_interval: 1s
    # On the ESP32 the voltage measured with the ADC caps out at ~1.1V by default as the sensing range (attenuation of the ADC) is set to 0db by default.
    # Measuring higher voltages requires setting attenuation to one of the following values: 0db, 2.5db, 6db, 12db. There’s more information at the manufacturer’s website.
    # https://docs.espressif.com/projects/esp-idf/en/v4.4.7/esp32/api-reference/peripherals/adc.html#_CPPv425adc1_config_channel_atten14adc1_channel_t11adc_atten_t
    # To simplify this, we provide the setting attenuation: auto for an automatic/seamless transition among scales. Our implementation combines all available ranges to allow the best resolution without having to compromise on a specific attenuation.
    attenuation: auto
    accuracy_decimals: 2
    filters:
      - multiply: 1.0  # Scale factor, modify based on your voltage divider